name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  microk8s:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.20', 1.19]

    steps:
      - uses: actions/checkout@v2
      - uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: ${{ matrix.version }}/stable
          addons: '["dns"]'
      - name: Test
        run: |
          kubectl get no
          kubectl get pods -A -o wide
      - name: Deploy
        run: |
          kubectl apply -f external-services.yaml
          kubectl wait --for condition=complete --timeout=10s -f external-services.yaml
      - name: Lookup GitHub
        run: |
          kubectl run -i --rm busybox --image=busybox --restart=Never -- nslookup github.com
          kubectl run -i --rm busybox --image=busybox --restart=Never -- nslookup github
